backend:
    name: github
    repo: josepbergay/flashjg-gatsby # Path to your GitHub repository
# backend:
#   name: git-gateway
#   branch: master

media_folder: static/img
public_folder: /img

collections:
    - name: "blog"
      label: "Blog"
      folder: "src/pages/blog"
      create: true
      slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
      fields:
          - {
                label: "Template Key",
                name: "templateKey",
                widget: "hidden",
                default: "blog-post",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Body", name: "body", widget: "markdown" }
          - { label: "Tags", name: "tags", widget: "list" }

    - name: "pages"
      label: "Pages"
      files:
          - file: "src/pages/index.md"
            label: "Página principal"
            name: "index"
            fields:
                - {
                      label: "Template Key",
                      name: "templateKey",
                      widget: "hidden",
                      default: "index-page",
                  }
                - { label: Título, name: title, widget: string }
                - { label: Subtítulo, name: subtitle, widget: string }
                - { label: Image, name: image, widget: image }
                - {
                      label: Mainpitch,
                      name: mainpitch,
                      widget: object,
                      fields:
                          [
                              { label: Title, name: title, widget: string },
                              {
                                  label: Description,
                                  name: description,
                                  widget: text,
                              },
                          ],
                  }
                - { label: Cabecera, name: heading, widget: string }
                - { label: Descripción, name: description, widget: string }
                - {
                      label: Campo cumpleaños,
                      name: birthdays,
                      widget: object,
                      fields:
                          [
                              { label: Nombre, name: name, widget: string },
                              { label: Imagen, name: image, widget: image },
                              {
                                  label: Cumpleaños,
                                  name: items,
                                  widget: list,
                                  fields:
                                      [
                                          {
                                              label: Fecha,
                                              name: date,
                                              widget: date,
                                          },
                                          {
                                              label: Nombre,
                                              name: name,
                                              widget: string,
                                          },
                                      ],
                              },
                          ],
                  }
                - {
                      label: Campo altas y bajas,
                      name: inandout,
                      widget: object,
                      fields:
                          [
                              {
                                  label: Altas,
                                  name: in,
                                  widget: list,
                                  fields:
                                      [
                                          {
                                              label: Nombre,
                                              name: name,
                                              widget: string,
                                          },
                                          {
                                              label: Ubicación,
                                              name: location,
                                              widget: string,
                                          },
                                          {
                                              label: Fecha incorporación,
                                              name: firstday,
                                              widget: date,
                                          },
                                      ],
                              },
                              {
                                  label: Baja,
                                  name: out,
                                  widget: list,
                                  fields:
                                      [
                                          {
                                              label: Nombre,
                                              name: name,
                                              widget: string,
                                          },
                                          {
                                              label: Ubicación,
                                              name: location,
                                              widget: string,
                                          },
                                          {
                                              label: Último día de trabajo,
                                              name: lastday,
                                              widget: date,
                                          },
                                      ],
                              },
                          ],
                  }
          # - file: "src/pages/about/index.md"
          #   label: "About"
          #   name: "about"
          #   fields:
          #       - {
          #             label: "Template Key",
          #             name: "templateKey",
          #             widget: "hidden",
          #             default: "about-page",
          #         }
          #       - { label: "Title", name: "title", widget: "string" }
          #       - { label: "Body", name: "body", widget: "markdown" }
          # - file: "src/pages/products/index.md"
          #   label: "Products Page"
          #   name: "products"
          #   fields:
          #       - {
          #             label: "Template Key",
          #             name: "templateKey",
          #             widget: "hidden",
          #             default: "product-page",
          #         }
          #       - { label: Title, name: title, widget: string }
          #       - { label: Image, name: image, widget: image }
          #       - { label: Heading, name: heading, widget: string }
          #       - { label: Description, name: description, widget: string }
          #       - {
          #             label: Intro,
          #             name: intro,
          #             widget: object,
          #             fields:
          #                 [
          #                     { label: Heading, name: heading, widget: string },
          #                     {
          #                         label: Description,
          #                         name: description,
          #                         widget: text,
          #                     },
          #                     {
          #                         label: Blurbs,
          #                         name: blurbs,
          #                         widget: list,
          #                         fields:
          #                             [
          #                                 {
          #                                     label: Image,
          #                                     name: image,
          #                                     widget: image,
          #                                 },
          #                                 {
          #                                     label: Text,
          #                                     name: text,
          #                                     widget: text,
          #                                 },
          #                             ],
          #                     },
          #                 ],
          #         }
          #       - {
          #             label: Main,
          #             name: main,
          #             widget: object,
          #             fields:
          #                 [
          #                     { label: Heading, name: heading, widget: string },
          #                     {
          #                         label: Description,
          #                         name: description,
          #                         widget: text,
          #                     },
          #                     {
          #                         label: Image1,
          #                         name: image1,
          #                         widget: object,
          #                         fields:
          #                             [
          #                                 {
          #                                     label: Image,
          #                                     name: image,
          #                                     widget: image,
          #                                 },
          #                                 {
          #                                     label: Alt,
          #                                     name: alt,
          #                                     widget: string,
          #                                 },
          #                             ],
          #                     },
          #                     {
          #                         label: Image2,
          #                         name: image2,
          #                         widget: object,
          #                         fields:
          #                             [
          #                                 {
          #                                     label: Image,
          #                                     name: image,
          #                                     widget: image,
          #                                 },
          #                                 {
          #                                     label: Alt,
          #                                     name: alt,
          #                                     widget: string,
          #                                 },
          #                             ],
          #                     },
          #                     {
          #                         label: Image3,
          #                         name: image3,
          #                         widget: object,
          #                         fields:
          #                             [
          #                                 {
          #                                     label: Image,
          #                                     name: image,
          #                                     widget: image,
          #                                 },
          #                                 {
          #                                     label: Alt,
          #                                     name: alt,
          #                                     widget: string,
          #                                 },
          #                             ],
          #                     },
          #                 ],
          #         }
          #       - {
          #             label: Testimonials,
          #             name: testimonials,
          #             widget: list,
          #             fields:
          #                 [
          #                     { label: Quote, name: quote, widget: string },
          #                     { label: Author, name: author, widget: string },
          #                 ],
          #         }
          #       - { label: Full_image, name: full_image, widget: image }
          #       - {
          #             label: Pricing,
          #             name: pricing,
          #             widget: object,
          #             fields:
          #                 [
          #                     { label: Heading, name: heading, widget: string },
          #                     {
          #                         label: Description,
          #                         name: description,
          #                         widget: string,
          #                     },
          #                     {
          #                         label: Plans,
          #                         name: plans,
          #                         widget: list,
          #                         fields:
          #                             [
          #                                 {
          #                                     label: Plan,
          #                                     name: plan,
          #                                     widget: string,
          #                                 },
          #                                 {
          #                                     label: Price,
          #                                     name: price,
          #                                     widget: string,
          #                                 },
          #                                 {
          #                                     label: Description,
          #                                     name: description,
          #                                     widget: string,
          #                                 },
          #                                 {
          #                                     label: Items,
          #                                     name: items,
          #                                     widget: list,
          #                                 },
          #                             ],
          #                     },
          #                 ],
          #         }
